version: '3'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
    # AMQP protocol port
    - "5672:5672"
    # HTTP management UI
    - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin